site_name: "LUMI training materials"
site_url: https://lumi-supercomputer.github.io/LUMI-training-materials

theme:
  name: material
  greetings: Welcome to the LUMI training materials"
  custom_dir: site_customisations
  language: en
  #logo: assets/favicon-LUMI.png
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips # Still only for insiders when added, so does not yet work.
  favicon: assets/favicon-LUMI.png
  font: false
  palette:
    scheme: default
    primary: lumi
    accent: lumi
  icon:
    logo: logo
    admonition:
      demo: fontawesome/solid/computer-mouse
      exercise: fontawesome/solid/screwdriver-wrench
      remark: fontawesome/solid/comment-dots
      bug: fontawesome/solid/robot
      audience: fontawesome/solid/people-group
      solution: fontawesome/solid/wand-magic-sparkles
      seealso: fontawesome/solid/link
      technical: fontawesome/solid/book-open-reader
      intermediate: fontawesome/solid/graduation-cap
      advanced: fontawesome/solid/user-graduate
      lumi-be: fontawesome/solid/building-flag
      nice-to-know: fontawesome/regular/lightbulb

nav:
  - Home: index.md
  - User Updates:
    - User-Updates/index.md
    - August-September 2024: 
      - User-Updates/Update-202409/index.md
      - FAQ: User-Updates/Update-202409/202409_FAQ.md
      - Documentation links: User-Updates/Update-202409/202409_Documentation.md
    - October-November 2023: User-Updates/Update-202311/index.md
    - August 2023: 
      - User-Updates/Update-202308/index.md
      - Low-noise mode: User-Updates/Update-202308/lumig-lownoise.md
      - dev-g and eap: User-Updates/Update-202308/lumig-devg.md
      - Responsible use: User-Updates/Update-202308/responsible-use.md
  - User Coffee Breaks:
    - User-Coffee-Breaks/index.md
  - Supercomputing with LUMI June 2025:
    - 2day-20250602/index.md
    - Schedule: 2day-20250602/schedule.md
    - Course materials: 2day-20250602/index.html#course-materials
  - AI workshop May 2025:
    - ai-20250527/index.md
    - Schedule: ai-20250527/schedule.md
    - Course materials: ai-20250527/index.html#course-materials
  - LUMI intensive March 2025:
    - 2p3day-20250303/index.md
    - Schedule: 2p3day-20250303/schedule.md
    - Course materials: 2p3day-20250303/index.html#course-materials
  - AI workshop February 2025:
    - ai-20250204/index.md
    - Schedule: ai-20250204/schedule.md
    - Course materials: ai-20250204/index.html#course-materials
  - Hackathon October 2024:
    - Hackathon-20241014/index.md
  - Profiling October 2024:
    - Profiling-20241009/index.md
  - Performance Analysis & Optimization June 2024:
    - paow-20240611/index.md
    - Schedule: paow-20240611/schedule.md
    - Course materials: paow-20240611/index.html#course-materials
  #- "Comprehensive LUMI NEXT": 
    #- Notes: 4day-2024next/notes_2_05_LUMI_Software_Stacks.md
  - Partner courses:
    - GROMACS workshop 2024: https://zenodo.org/records/10610643
  - Archive:
    - Supercomputing with LUMI December 2024:
      - 2day-20241210/index.md
      - Schedule: 2day-20241210/schedule.md
      - Course materials: 2day-20241210/index.html#course-materials
    - AI workshop November 2024:
      - ai-20241126/index.md
      - Schedule: ai-20241126/schedule.md
      - Course materials: ai-20241126/index.html#course-materials
    - Advanced LUMI October 2024:
      - 4day-20241028/index.md
      - Schedule: 4day-20241028/schedule.md
      - Course materials: 4day-20241028/index.html#course-materials
    - Supercomputing with LUMI May 2024:
      - 2day-20240502/index.md
      - Schedule: 2day-20240502/schedule.md
      - Course materials: 2day-20240502/index.html#course-materials
    - AI workshop May 2024:
      - ai-20240529/index.md
      - Schedule: ai-20240529/schedule.md
    - Comprehensive LUMI April 2024:
      - 4day-20240423/index.md
      - Schedule: 4day-20240423/schedule.md
    - "1-day February 2024":
      - 1day-20240208/index.md
      - LUMI Architecture: 1day-20240208/video_01_LUMI_Architecture.md
      - HPE Cray PE: 1day-20240208/video_02_HPE_Cray_Programming_Environment.md
      - Modules: 1day-20240208/video_03_Modules_on_LUMI.md
      - Software stacks: 1day-20240208/video_04_LUMI_Software_Stacks.md
      - Exercises 1: 1day-20240208/05_Exercises_1.md
      - Running jobs: 1day-20240208/video_06_Running_Jobs_on_LUMI.md
      - Exercises 2: 1day-20240208/07_Exercises_2.md
      - I/O and file systems: 1day-20240208/video_08_Introduction_to_Lustre_and_Best_Practices.md
      - LUMI support: 1day-20240208/video_09_LUMI_User_Support.md
      - Documentation: 1day-20240208/A01_Documentation.md
    - Profiling November 2023:
      - Profiling-20231122/index.md
    - Comprehensive LUMI October 2023:
      - 4day-20231003/index.md
    - "1-day September 2023":
      - 1day-20230921/index.md
      - LUMI Architecture: 1day-20230921/01_Architecture.md
      - HPE Cray PE: 1day-20230921/02_CPE.md
      - Modules: 1day-20230921/03_Modules.md
      - Software stacks: 1day-20230921/04_Software_stacks.md
      - Exercises 1: 1day-20230921/05_Exercises_1.md
      - Running jobs: 1day-20230921/06_Running_jobs.md
      - Exercises 2: 1day-20230921/07_Exercises_2.md
      - I/O and file systems: 1day-20230921/08_Lustre_intro.md
      - LUMI support: 1day-20230921/09_LUMI_support.md
      - Documentation: 1day-20230921/A01_Documentation.md
    - Comprehensive LUMI May-June 2023:
      - 4day-20230530/index.md
    - "1-day May 2023":
      - 1day-20230509/index.md
      - LUMI Architecture: 1day-20230509/01_Architecture.md
      - HPE Cray PE: 1day-20230509/02_CPE.md
      - Modules: 1day-20230509/03_Modules.md
      - Software stacks: 1day-20230509/04_Software_stacks.md
      - Exercises 1: 1day-20230509/05_Exercises_1.md
      - Running jobs: 1day-20230509/06_Running_jobs.md
      - Exercises 2: 1day-20230509/07_Exercises_2.md
      - I/O and file systems: 1day-20230509/08_Lustre_intro.md
      - LUMI support: 1day-20230509/09_LUMI_support.md
    - Hackathon April 2023:
      - hackathon: Hackathon-20230417/index.md
    - Profiling April 2013:
      - Profiling-20230413/index.md
    - Comprehensive LUMI February 2023:
      - 4day-20230214/index.md
    - "LUMI-G January 2023":
      - LUMI-G-20230111/index.md
    - PEAP-Q November 2022:
      - PEAP-Q-20221123/index.md
      - Schedule: PEAP-Q-20221123/schedule.md
    - LUMI-G August 2022:
      - LUMI-G-20220823/index.md
      - hackmd notes: LUMI-G-20220823/hackmd_notes.md
    - EasyBuild May 2022:
      - EasyBuild-CSC-20220509/index.md
      - Course notes: https://lumi-supercomputer.github.io/easybuild-tutorial/2022-CSC_and_LO/
    - PEAP-Q April 2022:
      - PEAP-Q-20220427/index.md
      - hackmd notes: PEAP-Q-20220427/hackmd_notes.md
      - LUMI Software Stacks: PEAP-Q-20220427/software_stacks.md

plugins:
  # show revision date at bottom of each page
  # - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  - redirects:
      redirect_maps:
          comprehensive-latest.md: 2p3day-20250303/index.md
          advanced-latest.md: 2p3day-20250303/index.md
          intro-latest.md: 2p3day-20250303/index.md
          AI-latest.md: ai-20250204/index.md
          ai-latest.md: ai-20250204/index.md
          update-202308.md: User-Updates/Update-202308/index.md
          update-202311.md: User-Updates/Update-202311/index.md
          update-202409.md: User-Updates/Update-202409/index.md
          #Amsterdam-1.md: 2day-20240502/E03_Exercises_1.md
          #Amsterdam-2.md: 2day-20240502/E04_Exercises_2.md
          #Amsterdam-3.md: 2day-20240502/E05_Exercises_3.md
          #Amsterdam-4.md: 2day-20240502/E07_Exercises_4.md

markdown_extensions:
  # Attributes (e.g., for lazy loading)
  - attr_list
  # Markdown in HTML
  - md_in_html
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # Caret notation for superscripts and inserts
  - pymdownx.caret
  # Smart symbols for TM etc, and automatic processing of 1st 2nd.
  # Beware for side effects as fractions such as 1/2 are also processed!
  - pymdownx.smartsymbols
  # tabbed contents
  - pymdownx.tabbed:
      alternate_style: true
  # Caret and tilde for superscript and subscript and other uses
  - pymdownx.caret
  - pymdownx.tilde
  # Mark extension to mark text.
  - pymdownx.mark
  # SmartSymbols (https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/)
  - pymdownx.smartsymbols
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Footnotes (https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes)
  - footnotes
  # Table of contents on the side
  - toc:
      permalink: true
  # More sophisticated tables: @span command.
  # Needs stylesheets from https://github.com/Neoteroi/mkdocs-plugins/releases/
  - neoteroi.spantable

extra_css:
  - stylesheets/extra.css
  # From https://github.com/Neoteroi/mkdocs-plugins/releases/tag/v0.0.6:
  - stylesheets/neoteroi-mkdocs.css
 
extra:
  # add links in bottom right
  social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCb31KOJ6Wqu0sRpIRi_k8Mw
      name: LUMI on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lumi-supercomputer
      name: LUMI on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc
      name: LUMI on Twitter
