site_name: "LUMI training materials"
site_url: https://github.com/klust/LUMI-training-materials

theme:
  name: material
  # logo: img/easybuild_logo.png
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  palette:
    - primary: black
  icon:
    admonition:
      demo: fontawesome/solid/computer-mouse
      exercise: fontawesome/solid/screwdriver-wrench
      remark: fontawesome/solid/comment-dots
      solution: fontawesome/solid/wand-magic-sparkles

nav:
  - Home: index.md
  - "1-day May 2023":
      - 1day-20230509/index.md
      - LUMI Architecture: 1day-20230509/01_Architecture.md
      - CPE: 1day-20230509/02_CPE.md
      - Lmod modules: 1day-20230509/03_Modules.md
      - Managing software: 1day-20230509/04_Software_stack.md
      - Exercises 1: 1day-20230509/05_Exercises_1.md
  - Profiling April 2013:
      - Profiling-20230413/index.md
  - Comprehensive LUMI February 2023:
      - 4day-20230214/index.md
  - "LUMI-G January 2023":
      - LUMI-G-20230111/index.md
  - PEAP-Q November 2022:
      - PEAP-Q-20221123/index.md
      - Schedule: PEAP-Q-20221123/schedule.md
      - HedgeDoc notes: PEAP-Q-20221123/hedgedoc_notes.md
      - LUMI Software Stacks: PEAP-Q-20221123/software_stacks.md
  - LUMI-G August 2022:
      - LUMI-G-20220823/index.md
      - hackmd notes: LUMI-G-20220823/hackmd_notes.md
  - EasyBuild May 2022:
      - EasyBuild-CSC-20220509/index.md
      - Course notes: https://klust.github.io/easybuild-tutorial/2022-CSC_and_LO/
  - PEAP-Q April 2022:
      - PEAP-Q-20220427/index.md
      - hackmd notes: PEAP-Q-20220427/hackmd_notes.md
      - LUMI Software Stacks: PEAP-Q-20220427/software_stacks.md

plugins:
  # show revision date at bottom of each page
  # - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  #- redirects:
  #    redirect_maps:
  #        practical_information.md: 2020-06-isc20/practical_information.md

markdown_extensions:
  # Attributes (e.g., for lazy loading)
  - attr_list
  # MArkdown in HTML
  - md_in_html
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
 
extra:
  # add links in bottom right
  social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCb31KOJ6Wqu0sRpIRi_k8Mw
      name: LUMI on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lumi-supercomputer
      name: LUMI on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc
      name: LUMI on Twitter
