site_name: "LUMI training materials"
site_url: https://lumi-supercomputer.github.io/LUMI-training-materials

theme:
  name: material
  greetings: Welcome to the LUMI training materials"
  custom_dir: site_customisations
  language: en
  #logo: assets/favicon-LUMI.png
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
    - content.code.annotate
  favicon: assets/favicon-LUMI.png
  font: false
  palette:
    scheme: default
    primary: lumi
    accent: lumi
  icon:
    logo: logo
    admonition:
      demo: fontawesome/solid/computer-mouse
      exercise: fontawesome/solid/screwdriver-wrench
      remark: fontawesome/solid/comment-dots
      solution: fontawesome/solid/wand-magic-sparkles

nav:
  - Home: index.md
  - User Updates:
      - User-Updates/index.md
      - October-November 2023: User-Updates/Update-202311/index.md
      - August 2023: 
          - User-Updates/Update-202308/index.md
          - Low-noise mode: User-Updates/Update-202308/lumig-lownoise.md
          - dev-g and eap: User-Updates/Update-202308/lumig-devg.md
          - Responsible use: User-Updates/Update-202308/responsible-use.md
  - User Coffee Breaks:
      - User-Coffee-Breaks/index.md
  - Profiling November 2023:
      - Profiling-20231122/index.md
  - Comprehensive LUMI October 2023:
      - 4day-20231003/index.md
  - "1-day September 2023":
      - 1day-20230921/index.md
      - LUMI Architecture: 1day-20230921/01_Architecture.md
      - HPE Cray PE: 1day-20230921/02_CPE.md
      - Modules: 1day-20230921/03_Modules.md
      - Software stacks: 1day-20230921/04_Software_stacks.md
      - Exercises 1: 1day-20230921/05_Exercises_1.md
      - Running jobs: 1day-20230921/06_Running_jobs.md
      - Exercises 2: 1day-20230921/07_Exercises_2.md
      - I/O and file systems: 1day-20230921/08_Lustre_intro.md
      - LUMI support: 1day-20230921/09_LUMI_support.md
      - Documentation: 1day-20230921/A01_Documentation.md
  - Comprehensive LUMI May-June 2023:
      - 4day-20230530/index.md
  - "1-day May 2023":
      - 1day-20230509/index.md
      - LUMI Architecture: 1day-20230509/01_Architecture.md
      - HPE Cray PE: 1day-20230509/02_CPE.md
      - Modules: 1day-20230509/03_Modules.md
      - Software stacks: 1day-20230509/04_Software_stacks.md
      - Exercises 1: 1day-20230509/05_Exercises_1.md
      - Running jobs: 1day-20230509/06_Running_jobs.md
      - Exercises 2: 1day-20230509/07_Exercises_2.md
      - I/O and file systems: 1day-20230509/08_Lustre_intro.md
      - LUMI support: 1day-20230509/09_LUMI_support.md
  - Hackathon April 2023:
      - hackathon: Hackathon-20230417/index.md
  - Profiling April 2013:
      - Profiling-20230413/index.md
  - Comprehensive LUMI February 2023:
      - 4day-20230214/index.md
  - "LUMI-G January 2023":
      - LUMI-G-20230111/index.md
  - PEAP-Q November 2022:
      - PEAP-Q-20221123/index.md
      - Schedule: PEAP-Q-20221123/schedule.md
  - LUMI-G August 2022:
      - LUMI-G-20220823/index.md
      - hackmd notes: LUMI-G-20220823/hackmd_notes.md
  - EasyBuild May 2022:
      - EasyBuild-CSC-20220509/index.md
      - Course notes: https://klust.github.io/easybuild-tutorial/2022-CSC_and_LO/
  - PEAP-Q April 2022:
      - PEAP-Q-20220427/index.md
      - hackmd notes: PEAP-Q-20220427/hackmd_notes.md
      - LUMI Software Stacks: PEAP-Q-20220427/software_stacks.md

plugins:
  # show revision date at bottom of each page
  # - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  - redirects:
      redirect_maps:
          comprehensive-latest.md: 4day-20231003/index.md
          intro-latest.md: 1day-20230921/index.md
          update-202308.md: User-Updates/Update-202308/index.md
          update-202311.md: User-Updates/Update-202311/index.md

markdown_extensions:
  # Attributes (e.g., for lazy loading)
  - attr_list
  # Markdown in HTML
  - md_in_html
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed:
      alternate_style: true
  # Table of contents on the side
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
 
extra:
  # add links in bottom right
  social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCb31KOJ6Wqu0sRpIRi_k8Mw
      name: LUMI on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lumi-supercomputer
      name: LUMI on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc
      name: LUMI on Twitter
